
%dw 2.0
output application/java 
---
[{
    SALE_GK : "velit",
    SALE_TS : |2017-01-08|,
    TRANSACTION_ID : 15,
    CHECK_NUMBER : 42,
    STORE_ID : 7,
    DATE_OF_BUSINESS : |2010-10-04|,
    SHACK_SCD_GK : "Ut",
    SHACK_ID : 62,
    GUEST_GK : "et",
    GUEST_TYPE : "in",
    GUEST_PURCHASING_STATUS : "minim",
    GUEST_FREQUENCY_STATUS : "voluptate",
    ORDER_MODE_ID : 73,
    ORDER_MODE_NAME : "modi",
    ORDER_MODE_CATEGORY : "ad",
    TENDER_ID : 82,
    TENDER_NAME : "labore",
    OLO_TENDER_NAME : "",
    TENDER_CASH_FLAG : "vitae",
    COUPON_CODE : "porro",
    COUPON_DESCRIPTION : "voluptas",
    AMOUNT_ITEM_SALES : 76,
    AMOUNT_DISCOUNT : 25,
    AMOUNT_PAID : 98,
    AMOUNT_TAX : 59,
    AMOUNT_NET : 60,
    INS_TS : |2008-04-19|,
    UPD_TS : |2011-01-26|,
    ORDER_MODE_SUBCATEGORY : "fugit,",
  },
{
    SALE_GK : "cupidatat",
    SALE_TS : |2004-10-18|,
    TRANSACTION_ID : 11,
    CHECK_NUMBER : 82,
    STORE_ID : 23,
    DATE_OF_BUSINESS : |2014-05-27|,
    SHACK_SCD_GK : "beatae",
    SHACK_ID : 77,
    GUEST_GK : "ut",
    GUEST_TYPE : "dicta",
    GUEST_PURCHASING_STATUS : "consequatur,",
    GUEST_FREQUENCY_STATUS : "inventore",
    ORDER_MODE_ID : 61,
    ORDER_MODE_NAME : "aut",
    ORDER_MODE_CATEGORY : "quia",
    TENDER_ID : 62,
    TENDER_NAME : "pariatur?",
    OLO_TENDER_NAME : "amet,",
    TENDER_CASH_FLAG : "dolor",
    COUPON_CODE : "et",
    COUPON_DESCRIPTION : "omnis",
    AMOUNT_ITEM_SALES : 73,
    AMOUNT_DISCOUNT : 73,
    AMOUNT_PAID : 77,
    AMOUNT_TAX : 30,
    AMOUNT_NET : 36,
    INS_TS : |2007-06-17|,
    UPD_TS : |2004-09-23|,
    ORDER_MODE_SUBCATEGORY : "ex",
  }]
